# Generated by Django 4.1.7 on 2023-05-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email', models.EmailField(max_length=254)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('report_text', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'المعلمين', 'verbose_name_plural': 'المعلمين'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'مشاريع', 'verbose_name_plural': 'مشاريع'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'مهمات', 'verbose_name_plural': 'مهمات'},
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(1, 'قيد  التنفيذ'), (2, 'مكتمل'), (3, 'معلق'), (4, 'ملغي')], default=1),
        ),
    ]
