# Generated by Django 4.1.7 on 2023-05-04 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_report_alter_category_options_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'ارسال التقارير', 'verbose_name_plural': 'ارسال التقارير'},
        ),
    ]
